name: Checkmarx api integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  security-events: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkmarx scan
        uses: checkmarx/ast-github-action@main
        with:
          base_uri: https://deu.iam.checkmarx.net/
          cx_client_id: ${{ secrets.cxclientid }}
          cx_client_secret: ${{ secrets.cxclientsecret }}
          cx_tenant: ${{ secrets.cxtenant }}


      - name: Fetch results
        run: 
          docker run --rm -it \
            -e API_KEY=${{secrets.cxapikey}} \
            -e PROJECT_NAME=udit-uniyal/DVWA \
            -e REPORT_PATH=/app/data/ \
            -v $PWD:/app/data/ \
            accuknox/checkmarxjob:1.0.4

      - name: Upload SARIF file with code snippets
        uses: actions/upload-artifact@v3
        with:
          name: sarif-results-with-snippets
          path: cx_result.json

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: cx_result.json

      - name: Push SARIF file to CSPM panel
        run: |
          curl --location '${{ secrets.CSPM_URL }}/api/v1/artifact/?tenant_id=${{ secrets.TENANT_ID }}&data_type=CMX&save_to_s3=true&label_id=${{ secrets.LABEL_ID }}' \
            --header 'Tenant-Id: ${{ secrets.TENANT_ID }}' \
            --header 'Authorization: Bearer ${{ secrets.CSPM_TOKEN }}' \
            --form 'file=@./tmp_sarif_with_snippets.sarif'